### ISSUE TITLE
Timer Event difference is not recognized.

### ISSUE THREAD

**Issue by stocksanjan** [bpmn-io/bpmn-js-differ#14]
Timer Event differences are not being shown as output from this framework.

Please create clones BPMNs with timer event with default event duration as PT1S, and change the timer event's duration to PT5S on one of the BPMN File.
Now upload both the files to see the list of
[diagram_1.zip](https://github.com/bpmn-io/bpmn-js-differ/files/9502255/diagram_1.zip)
 changes and the frame work wouldn't really differenciate on the files.

**Comment by pinussilvestrus** [comment]
Please use one of our existing[ issue templates](https://github.com/bpmn-io/bpmn-js-differ/issues/new/choose). Without it, we won't be able to help you properly.

**Comment by pinussilvestrus** [comment]
@stocksanjan are you able to give the necessary details? If not, we will likely close this issue.

**Comment by stocksanjan** [comment]
Submitted the issue here: https://github.com/bpmn-io/bpmn-js-differ/issues/15
