### ISSUE TITLE
https://demo.bpmn.io/diff is not working now

### ISSUE THREAD

**Issue by KillWolfVlad** [bpmn-io/bpmn-js-differ#16]
### Describe the Bug

https://demo.bpmn.io/diff is not working now.

![image](https://github.com/bpmn-io/bpmn-js-differ/assets/18448635/b7f25841-c735-4dd1-9b4d-fd5c9f4b7410)

### Steps to Reproduce

1. Go to https://demo.bpmn.io/diff
2. Upload two schemas
3. Nothing happening, white screen

### Expected Behavior

Site is working and show diff

### Environment

- Host (Browser/Node version), if applicable: Any
- OS: Any
- Library version: N/A

**Comment by KillWolfVlad** [comment]
I would help you with this bug - or deploy previous working version. But I don't know were source code of this site?

**Comment by nikku** [comment]
Thanks for reporting. We'll look into the issue.

**Comment by nikku** [comment]
This is fixed via an update to our demo.

**Comment by KillWolfVlad** [comment]
Thank you! Everything is working. But I don't see any PR linked to this issue. Is source code of demo site is not open source?

**Comment by initshdb** [comment]
@nikku  Is the demo site opensource to be run locally?

**Comment by nikku** [comment]
No, unfortunately the demo is not open source. But we considered to simply put up a diffing example on our [examples](https://github.com/bpmn-io/bpmn-js-examples). We just did not get to that, yet.
