### ISSUE TITLE
Diff method did not find changes on two completely different process definitions

### ISSUE THREAD

**Issue by robpal94** [bpmn-io/bpmn-js-differ#7]
The `diff` Method returns the same results, when comparing two models, that are exactly the same and two completely different models with different collaborations.

Consider the following two process definitions:
[process1](https://gist.github.com/robpal94/b4541a71612a233e8f2d0ec5103d1fa4)
[process2](https://gist.github.com/robpal94/846c153f6bb2d50c0531ccb802edb343)

When calling the `diff()` method on both of these processes, I would not expect a result that looks like, both processes are the same (or that there are no changes). 
The current behavior makes it very hard to distinguish, if two compared processes are the same or if these are actually complete different processes.

**Comment by nikku** [comment]
Please provide a [failing test case](https://github.com/bpmn-io/bpmn-js-differ/blob/master/test/spec/differ.js) with what you'd expect the differ to output.

**Comment by robpal94** [comment]
Basically it would be nice, if an exception is thrown to let the user of this library know, when two processes are not comparable. Like so: 

https://github.com/robpal94/bpmn-js-differ/blob/master/test/spec/differ.js#L401

**Comment by nikku** [comment]
I don't quite agree with your notion of _not comparable_. 

The diagrams are comparable:

* equal on the `bpmn:Definitions` level (both with the ID `Definitions_1`)
* diverging on the `bpmn:Collaboration` level

Because of this I'd rather mark the collaboration as added / removed than throwing an exception.

**Comment by nikku** [comment]
__Proposal:__ We talk about the collaboration being added or removed, visually speaking:

![image](https://user-images.githubusercontent.com/58601/42985964-f28784f6-8bf3-11e8-9a43-bf01b8b3042f.png)

Works when diffing process with collaboration diagrams, too:

![image](https://user-images.githubusercontent.com/58601/42985982-0a76bdca-8bf4-11e8-9c2c-ca10bc618ca5.png)

**Comment by robpal94** [comment]
I also thought at this while I was on my way home. This would also be a good Idea, probably better then marking two diagrams as incomparable. Is such a feature currently implemented?
