### ISSUE TITLE
demo licence

### ISSUE THREAD

**Issue by bigianb** [bpmn-io/bpmn-js-differ#9]
I notice that the https://demo.bpmn.io/diff site uses this ... in fact it is a very small wrapper around it along with some CSS.
Is the code available somewhere? If I were to use the code from that site as a starting point for something else then the licence is not clear. Would you be willing to clarify it please?

**Comment by nikku** [comment]
The code that produces [demo.bpmn.io](https://demo.bpmn.io) is not available for copying / under an open-source license. We hope that it inspires you. You should not simply steal it though but build your own solution around this library.

**Comment by bigianb** [comment]
Is it available via a paid or closed source licence? Just interested in the diff bit for an in house app. No intention to steal it but would like to save some implementation time via a licence for the existing code

**Comment by nikku** [comment]
I understand you, cannot offer you something at the moment though.
